const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('test deployment config is isolated, mock-only, and contains no production target', () => {
  const config = JSON.parse(read('cloudbaserc.style-preview-test.json'))
  assert.equal(config.envId, 'shengjing-style-test-d3ac90f38b1')
  assert.equal(JSON.stringify(config).includes('cloud1-d4g7zh8kpca0e26d5'), false)
  assert.equal(config.functions.length, 2)
  assert.deepEqual(config.functions.map((item) => item.name), ['stylePreviewApi', 'processStylePreviewTask'])
  assert.equal(config.functions[0].envVariables.STYLE_PREVIEW_PROVIDER, 'mock')
  assert.equal(config.functions[0].envVariables.STYLE_PREVIEW_REAL_AI_ENABLED, 'false')
})

test('deployment script refuses an implicit or production target before invoking CloudBase', () => {
  const script = read('scripts/deploy-style-preview-v2-test.mjs')
  assert.match(script, /pass exactly --env shengjing-style-test-d3ac90f38b1/)
  assert.match(script, /target !== TEST_ENV/)
  assert.match(script, /PRODUCTION_DATA_ACCESS=false/)
  assert.match(script, /stylePreviewApi/)
  assert.match(script, /processStylePreviewTask/)
  assert.match(script, /style_preview_sessions/)
  assert.match(script, /style_preview_tasks/)
  assert.match(script, /tenant_idempotency_unique/)
  assert.doesNotMatch(script, /submitStageLog|reviewStageLog|sendOwnerNotice|listMyProjects/)
})

test('real pages require server access while Mock remains a separate explicit branch', () => {
  const start = read('miniprogram/subpackages/style-preview/pages/start/index.js')
  const processing = read('miniprogram/subpackages/style-preview/pages/processing/index.js')
  assert.match(start, /String\(options\.mock \|\| ''\) === '1'/)
  assert.match(start, /realService\.checkAccess\(\)/)
  assert.match(processing, /realService\.getTask/)
  assert.match(processing, /mockService\.completeSession/)
})

test('server task code has tenant gates, idempotency, safe errors, and transactional claiming', () => {
  const api = read('cloudfunctions/stylePreviewApi/index.js')
  const worker = read('cloudfunctions/processStylePreviewTask/index.js')
  assert.match(api, /STYLE_PREVIEW_FEATURE_ENABLED === 'true'/)
  assert.match(api, /idempotencyKey/)
  assert.match(api, /STYLE_PREVIEW_TENANT_DAILY_LIMIT/)
  assert.match(api, /cloud\.downloadFile/)
  assert.match(worker, /db\.runTransaction/)
  assert.match(worker, /context\.OPENID/)
  assert.match(worker, /status: 'succeeded'/)
})
